services:
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        image: hentaigames-app
        container_name: hentaigames_app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - hentaigames_network

    web:
        image: nginx:alpine
        container_name: hentaigames_nginx
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
        networks:
            - hentaigames_network
        depends_on:
            - app

networks:
    hentaigames_network:
        driver: bridge